In [1]:
import numpy as np

In [17]:
a = np.array([[1.],[1.],[1.],[1.],[1.],[1.],[1.],[1.],[1.],[1.]])
print(f'This is a column vector:{a} \n and this is a row vector{a.T}')

This is a column vector:[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]] 
 and this is a row vector[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [26]:
# a = np.ones(9)

b = np.arange(1,10)
print(b)

[1 2 3 4 5 6 7 8 9]


In [19]:
a.shape

(10, 1)

In [20]:
a_ = a.T
print(f'The shape of a is {a.shape} and the shape of a transpose {a_.shape}')

The shape of a is (10, 1) and the shape of a transpose (1, 10)


In [27]:
a.dot(b.T)

ValueError: shapes (10,1) and (9,) not aligned: 1 (dim 1) != 9 (dim 0)

In [28]:
mat_a = np.array([
    [1,2],
    [3,4]
])

In [29]:
mat_a.shape

(2, 2)

In [30]:
mat_a.T

array([[1, 3],
       [2, 4]])

In [31]:
mat_b = ([
    [4,5],
    [7,6]
])

In [33]:
mat_I = np.array([
    [1,0],
    [0,1]
])

In [34]:
mat_a @ mat_I

array([[1, 2],
       [3, 4]])

In [37]:
mat_a * (2 * mat_I)

array([[2, 0],
       [0, 8]])

In [45]:
sqrt_2_vr = np.array([np.sqrt(2), np.sqrt(2), np.sqrt(2)])
sqrt_2_vc = np.array([[np.sqrt(2)], [np.sqrt(2)], [np.sqrt(2)]])
print(sqrt_2_vc)

[[1.41421356]
 [1.41421356]
 [1.41421356]]


In [48]:
sqrt_2_vr @ sqrt_2_vc

array([6.])

In [49]:
complex_row = np.array([[1+2j],[2+3j],[4+5j]])

In [54]:
complex_matrix = np.array([
    [1+2j, 2+3j, 4+5j],
    [6+2j,4+1j,2+0j]
])

In [55]:
complex_matrix

array([[1.+2.j, 2.+3.j, 4.+5.j],
       [6.+2.j, 4.+1.j, 2.+0.j]])

In [58]:
complex_matrix @ complex_row

array([[-17.+56.j],
       [ 15.+38.j]])