# Vectors

Vectors are lists of numbers (computer science) or a measure of a magintude and an associated direction. A refresher on vectors is available at [Vectors](https://www.youtube.com/watch?v=fNk_zzaMoSs)

In [2]:
import numpy as np # import numpy to create all the type of orders lists of numbers below 

You can create a vector using numpy arrays

$$
a = 
\begin{bmatrix}
    1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 \\
\end{bmatrix}
$$

In [4]:
a = np.array([[1],[1],[1],[1],[1],[1],[1],[1],[1],[1]])

In [5]:
a = np.ones(9)

In [6]:
b = np.arange(1,10)

In [7]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

You can work out the shape of your vector as below

In [8]:
a.shape

(9,)

You can have two types of vectors a row vector and a column vector. 

$$
row-vector = 
\begin{bmatrix}
    1 & 1 & 1  \\
\end{bmatrix}
$$

$$
column-vector = 
\begin{bmatrix}
    1 \\
    1 \\
    1 \\
\end{bmatrix}
$$

You can switch between the two using the Transpose (.T) operator as below


In [11]:
b.T.shape

(9,)

Notice the shape is now (9,) and not (,9) as before 



When you multiply a row vector and a column vector together you get a number. Thanks to python you don't need to remember the rules of how to do this, just have fun with numpy. To do a product between two vectors you can do the following

In [47]:
a.dot(b.T)

45.0

An alternative way of doing that - which is really elegant (thanks python) is to use the @ symbol as below:

In [51]:
a @ b.T

45.0

# Matrices

Matrices are sets of numbers ordered into rows and columns (kind of like a table). You can review Manning Author Grant Sanderson's video on Linear Algebra to understand matrices and matrix multiplication better. [Grant's Videos](https://www.youtube.com/watch?v=XkY2DOUCWMU)

In [20]:
mat_a = np.array([
        [1,2],
        [3,4]  
])

as will vector's you can determine the shape of a matric as such

In [21]:
mat_a.shape

(2, 2)

In [22]:
mat_a

array([[1, 2],
       [3, 4]])

and also you can transpose a matrix using the .T operator

In [23]:
mat_a.T

array([[1, 3],
       [2, 4]])

notice that mat_a.T has two of the elements switched (2 -> 3 and 3 -> 2)

In [24]:
mat_a.T.T

array([[1, 2],
       [3, 4]])

if you double transpose, your return back to the same matrix as you began with (wow math works!)

In [25]:
mat_b = ([
    [4,5],
    [7,6]
])

The matrix (I) shown below is a little special. Any matrix multiplied by I is itself. Hence it is known as the identiy matrix

In [26]:
mat_I = np.array([
    [1,0],
    [0,1]
])

In [27]:
mat_a @ mat_I

array([[1, 2],
       [3, 4]])

and I is also it's own transpose 

In [28]:
mat_I.T

array([[1, 0],
       [0, 1]])

In [31]:
if np.allclose(mat_I, mat_I.T):
    print("The identity matrix is it's own transpose - you know it!😜")

The identity matrix is it's own transpose - you know it!😜


In [70]:
mat_a + mat_b

array([[ 5,  7],
       [10, 10]])

You can work out common matrix relationships such as the property below. The np.allclose() method allows you to compare two separate matrices to see if they are equivalent. Using this your can work out some common properties.

In [71]:
np.allclose( mat_a @ mat_I + mat_b, mat_a + mat_b @ mat_I)

True

In [72]:
if np.allclose(mat_I,mat_I):
#   The identity matrix is is own transpose
    print('Hello Identity')

Hello Identity


## Vectors and Matrices

You can use vectors and matrices together. But you have to be careful with the shapes. 

In [44]:
vec_c = np.array([1,2,3])
vec_c.shape

(3,)

In [45]:
matrix_c = np.array([[1,0],
                    [0,1],
                    [1,1]])
matrix_c.shape

(3, 2)

In [46]:
vec_c @ matrix_c

array([4, 5])

similarily you can multiply a matrix and a column vectors in this way. Notice the Matrix comes first and then the vector. This is to do with the rules of matrix multiplication that numpy knows. 

In [58]:
matrix_d = np.array([
    [0,1],
    [1,0]
])

In [59]:
vec_d = np.array([1,1])

In [60]:
matrix_d @ vec_d.T

array([1, 1])

## Vectors and Complex Numbers

Just for completeness you can create vectors (

In [12]:
complex_vector_a = np.array([
    [1+2j, 2+3j]
])

In [13]:
complex_vector_a

array([[1.+2.j, 2.+3.j]])

# Exercises

1) Can you create a row matrix of 3 elements $$ \sqrt{2} $$ and a similar row vector. Can you do a a dot product (@) of both vectors? What is the number?

In [11]:
import math
root_2 = math.sqrt(2)
ex_1 = ex_2 = np.array([root_2, root_2, root_2])
ex_1 @ ex_2.T

6.000000000000002

2) Can you create the following matrices in code and multiply them together?

$$
\begin{bmatrix}
1+2i \\
2+3i \\
4+5i\\ 
\end{bmatrix}$$

$$
\begin{bmatrix}
1 + 2j & 2 + 3j & 4 + 5j \\
6 + 7j & 4 + 1j & 2 + 0j \\
\end{bmatrix}
$$

In [3]:
matrix_1 = np.array([
    [1+2j, 2+3j, 4 + 5j],
    [6+7j, 4+1j, 2]
])

In [4]:
matrix_2 = np.array([
    [1 + 2j],
    [2 + 3j],
    [4 + 5j]
])

In [5]:
matrix_1 @ matrix_2

array([[-17.+56.j],
       [  5.+43.j]])